export enum Role {
  SUPERADMIN = 'SUPERADMIN',
  ADMIN_FREE = 'ADMIN',
  ADMIN_BASIC = 'ADMIN_BASIC',
  ADMIN_PREMIUM = 'ADMIN_PREMIUM',
  LECTURER_FREE = 'LECTURER',
  LECTURER_BASIC = 'LECTURER_BASIC',
  LECTURER_PREMIUM = 'LECTURER_PREMIUM',
  STUDENT = 'STUDENT',
}
